apiVersion: 1
groups:
    - orgId: 1
      name: Alerts
      folder: Alerts
      interval: 1m
      rules:
        - uid: ceq74fd2xjj0ga
          title: Attack Probability Too High
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P31C819B24CF3C3C7
              model:
                alias: ""
                bucketAggs:
                    - field: '@timestamp'
                      id: "2"
                      settings:
                        interval: auto
                      type: date_histogram
                intervalMs: 1000
                maxDataPoints: 43200
                metrics:
                    - field: all_probabilities.Unknown_Attack
                      id: "1"
                      type: avg
                query: ""
                refId: A
                timeField: '@timestamp'
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: sahil_email
