apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: ddos_predictions
    isDefault: true
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.14.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: log_level
    secureJsonData: {} 